// dap/status_text.cc -- text for DAP status codes.
//
// Generated from the tables in PyDECnet's dap_packets.py (Status.maccodes,
// miccodes_289, miccodes_rms and miccodes_10).  Codes are octal, as the
// DAP specification writes them.

#include "decnet/dap/messages.h"

#include <algorithm>
#include <cstdio>
#include <iterator>

namespace decnet::dap {

namespace {

struct Text {
    unsigned    code;
    const char *text;
};

const Text maccodes[] = {
    { 00, "Pending" },
    { 01, "Success" },
    { 02, "Unsupported" },
    { 04, "Open error" },
    { 05, "Transfer error" },
    { 06, "Transfer warning" },
    { 07, "Close error" },
    { 010, "Message format error" },
    { 011, "Invalid field" },
    { 012, "Out of sync" },
};

const Text miccodes_289[] = {
    { 00, "Unspecified DAP message error." },
    { 010, "DAP message type field (TYPE) error." },
    { 0100, "Unknown field." },
    { 0110, "DAP message flags field (FLAGS)." },
    { 0111, "Data stream identification field (STREAMID)." },
    { 0112, "Length field (LENGTH)." },
    { 0113, "Length extension field (LEN256)." },
    { 0114, "BITCNT field (BITCNT)." },
    { 0120, "Buffer size field (BUFSIZ)." },
    { 0121, "Operating system type field (OSTYPE)." },
    { 0122, "File system type field (FILESYS)." },
    { 0123, "DAP version number field (VERNUM)." },
    { 0124, "ECO version number field (ECONUM)." },
    { 0125, "USER protocol version number field (USRNUM)." },
    { 0126, "DEC software release number field (SOFTVER)." },
    { 0127, "User software release number field (USRSOFT)." },
    { 0130, "System capabilities field (SYSCAP)." },
    { 0200, "Unknown field." },
    { 0210, "DAP message flags field (FLAGS)." },
    { 0211, "Data stream identification field (STREAMID)." },
    { 0212, "Length field (LENGTH)." },
    { 0213, "Length extension field (LEN 256)." },
    { 0214, "Bit count field (BITCNT)." },
    { 0215, "System specific field (SYSPEC)." },
    { 0220, "Attributes menu field (ATTMENU)." },
    { 0221, "Data type field (DATATYPE)." },
    { 0222, "File organization field (ORG)." },
    { 0223, "Record format field (RFM)." },
    { 0224, "Record attributes field (RAT)." },
    { 0225, "Block size field (BLS)." },
    { 0226, "Maximum record size field (MRS)." },
    { 0227, "Allocation quantity field (ALQ)." },
    { 0230, "Bucket size field (BKS)." },
    { 0231, "Fixed control area size field (FSZ)." },
    { 0232, "Maximum record number field (MRN)." },
    { 0233, "Run-time system field (RUNSYS)." },
    { 0234, "Default extension quantity field (DEQ)." },
    { 0235, "File options field (FOP)." },
    { 0236, "Byte size field (BSZ)." },
    { 0237, "Device characteristics field (DEV)." },
    { 0240, "Spooling device characteristics field (SDC)." },
    { 0241, "Longest record length field (LRL)." },
    { 0242, "Highest virtual block allocated field (HBK)." },
    { 0243, "End of file block field (EBK)." },
    { 0244, "First free byte field (FFB)." },
    { 0245, "Starting LBN for contiguous file (SBN)." },
    { 0300, "Unknown field." },
    { 0310, "DAP message flags field (FLAGS)." },
    { 0311, "Data stream identification field (STREAMID)." },
    { 0312, "Length field (LENGTH)." },
    { 0313, "Length extension field (LEN256)." },
    { 0314, "Bit count field (BITCNT)." },
    { 0315, "System specific field (SYSPEC). ." },
    { 0320, "Access function field (ACCFUNC)." },
    { 0321, "Access options field (ACCOPT)." },
    { 0322, "File specification field (FILESPEC)." },
    { 0323, "File access field (FAC)." },
    { 0324, "File sharing field (SHR)." },
    { 0325, "Display attributes request field (DISPLAY)." },
    { 0326, "File password field (PASSWORD)." },
    { 0400, "Unknown field." },
    { 0410, "DAP message flags field (FLAGS)." },
    { 0411, "Data stream identification field (STREAMID)." },
    { 0412, "Length field (LENGTH)." },
    { 0413, "Length extension field (LEN256)." },
    { 0414, "Bit count field (BITCNT)." },
    { 0415, "System specific field (SYSPEC). ." },
    { 0420, "Control function field (CTLFUNC)." },
    { 0421, "Control menu field (CTLMENU)." },
    { 0422, "Record access field (RAC)." },
    { 0423, "Key field (KEY)." },
    { 0424, "Key of reference field (KRF)." },
    { 0425, "Record options field (ROP)." },
    { 0426, "Hash code field (HSH)." },
    { 0427, "Display attributes request field (DISPLAY)." },
    { 0500, "Unknown field." },
    { 0510, "DAP message flags field (FLAGS)." },
    { 0511, "Data stream identification field (STREAMID)." },
    { 0512, "Length field (LENGTH)." },
    { 0513, "Length extension field (LEN256)." },
    { 0514, "Bit count field (BITCNT)." },
    { 0515, "System specific field (SYSPEC)." },
    { 0520, "Continue transfer function field (CONFUNC)." },
    { 0600, "Unknown field." },
    { 0610, "DAP message flags field (FLAGS)." },
    { 0611, "Data stream identification field (STREAMID)." },
    { 0612, "Length field (LENGTH)." },
    { 0613, "Length extension field (LEN256)." },
    { 0614, "Bit count field (BITCNT)." },
    { 0615, "System specific field (SYSPEC)." },
    { 0700, "Unknown field." },
    { 0710, "DAP message flags field (FLAGS)." },
    { 0711, "Data stream identification field (STREAMID)." },
    { 0712, "Length field (LENGTH)." },
    { 0713, "Length extension field (LEN256)." },
    { 0714, "Bit count field (BITCNT)." },
    { 0715, "System specific field (SYSPEC)." },
    { 0720, "Access complete function field (CMPFUNC)." },
    { 0721, "File options field (FOP)." },
    { 0722, "Checksum field (CHECK)." },
    { 01000, "Unknown field." },
    { 01010, "DAP message flags field (FLAGS)." },
    { 01011, "Data stream identification field (STREAMID)." },
    { 01012, "Length field (LENGTH)." },
    { 01013, "Length extension field (LEN256)." },
    { 01014, "Bit count field (BITCNT)." },
    { 01015, "System specific field (SYSPEC)." },
    { 01020, "Record number field (RECNUM)." },
    { 01021, "File data field (FILEDATA)." },
    { 01100, "Unknown field." },
    { 01110, "DAP message flags field (FLAGS)." },
    { 01111, "Data stream identification field (STREAMID)." },
    { 01112, "Length field (LENGTH)." },
    { 01113, "Length extension field (LEN256)." },
    { 01114, "Bit count field (BITCNT)." },
    { 01115, "System specific field (SYSPEC)." },
    { 01120, "Macro status code field (MACCODE)." },
    { 01121, "Micro status code field (MICCODE)." },
    { 01122, "Record file address field (RFA)." },
    { 01123, "Record number field (RECNUM)." },
    { 01124, "Secondary status field (STV)." },
    { 01200, "Unknown field." },
    { 01210, "DAP message flags field (FLAGS)." },
    { 01211, "Data stream identification field (STREAMID)." },
    { 01212, "Length field (LENGTH)." },
    { 01213, "Length extension field (LEN256)." },
    { 01214, "Bit count field (BITCNT)." },
    { 01215, "System specific field (SYSPEC)." },
    { 01220, "Key definition menu field (KEYMENU)." },
    { 01221, "Key option flags field (FLG)." },
    { 01222, "Data bucket fill quantity field (DFL)." },
    { 01223, "Index bucket fill quantity field (IFL)." },
    { 01224, "Key segment repeat count field (SEGCNT)." },
    { 01225, "Key segment position field (POS)." },
    { 01226, "Key segment size field (SIZ)." },
    { 01227, "Key of reference field (REF)." },
    { 01230, "Key name field (KNM)." },
    { 01231, "Null key character field (NUL)." },
    { 01232, "Index area number field (IAN)." },
    { 01233, "Lowest level area number field (LAN)." },
    { 01234, "Data level area number field (DAN)." },
    { 01235, "Key data type field (DTP)." },
    { 01236, "Root VBN for this key field (RVB)." },
    { 01237, "Hash algorithm value field (HAL)." },
    { 01240, "First data bucket VBN field (DVB)." },
    { 01241, "Data bucket size field (DBS)." },
    { 01242, "Index bucket size field (IBS)." },
    { 01243, "Level of root bucket field (LVL)." },
    { 01244, "Total key size field (TKS)." },
    { 01245, "Minimum record size field (MRL)." },
    { 01300, "Unknown field." },
    { 01310, "DAP message flags field (FLAGS)." },
    { 01311, "Data stream identification field (STREAMID)." },
    { 01312, "Length field (LENGTH)." },
    { 01313, "Length extension field (LEN256)." },
    { 01314, "Bit count field (BITCNT)." },
    { 01315, "System specific field (SYSPEC)." },
    { 01320, "Allocation menu field (ALLMENU)." },
    { 01321, "Relative volume number field (VOL)." },
    { 01322, "Alignment options field (ALN)." },
    { 01323, "Allocation options field (AOP)." },
    { 01324, "Starting location field (LOC)." },
    { 01325, "Related file identification field (RFI)." },
    { 01326, "Allocation quantity field (ALQ)." },
    { 01327, "Area identification field (AID)." },
    { 01330, "Bucket size field (BKZ)." },
    { 01331, "Default extension quantity field (DEQ)." },
    { 01400, "Unknown field." },
    { 01410, "DAP message flags field (FLAGS)." },
    { 01411, "Data stream identification field (STREAMID)." },
    { 01412, "Length field (LENGTH)." },
    { 01413, "Length extension field (LEN256)." },
    { 01414, "Bit count field (BITCNT)." },
    { 01415, "System specific field (SYSPEC)." },
    { 01420, "Summary menu field (SUMENU)." },
    { 01421, "Number of keys field (NOK)." },
    { 01422, "Number of areas field (NOA)." },
    { 01423, "Number of record descriptors field (NOR)." },
    { 01424, "Prologue version number (PVN)." },
    { 01500, "Unknown field." },
    { 01510, "DAP message flags field (FLAGS)." },
    { 01511, "Data stream identification field (STREAMID)." },
    { 01512, "Length field (LENGTH)." },
    { 01513, "Length extension field (LEN256)." },
    { 01514, "Bit count field (BITCNT)." },
    { 01515, "System specific field (SYSPEC)." },
    { 01520, "Date and time menu field (DATMENU)." },
    { 01521, "Creation date and time field (CDT)." },
    { 01522, "Last update date and time field (RDT)." },
    { 01523, "Deletion date and time field (EDT)." },
    { 01524, "Revision number field (RVN)." },
    { 01600, "Unknown field." },
    { 01610, "DAP message flags field (FLAGS)." },
    { 01611, "Data stream identification field (STREAMID)." },
    { 01612, "Length field (LENGTH)." },
    { 01613, "Length extension field (LEN256)." },
    { 01614, "Bit count field (BITCNT)." },
    { 01615, "System specific field (SYSPEC)." },
    { 01620, "Protection menu field (PROTMENU)." },
    { 01621, "File owner field (OWNER)." },
    { 01622, "System protection field (PROTSYS)." },
    { 01623, "Owner protection field (PROTOWN)." },
    { 01624, "Group protection field (PROTGRP)." },
    { 01625, "World protection field (PROTWLD)." },
    { 01700, "Unknown field." },
    { 01710, "DAP message flags field (FLAGS)." },
    { 01711, "Data stream identification field (STREAMID)." },
    { 01712, "Length field (LENGTH)." },
    { 01713, "Length extension field (LEN256)." },
    { 01714, "Bit count field (BITCNT)." },
    { 01715, "System specific field (SYSPEC)." },
    { 01720, "Name type field (NAMETYPE)." },
    { 01721, "Name field (NAMESPEC)." },
    { 02000, "Unknown field." },
    { 02010, "DAP message flags field (FLAGS)." },
    { 02011, "Data stream identification field (STREAMID)." },
    { 02012, "Length field (LENGTH)." },
    { 02013, "Length extension field (LEN256)." },
    { 02014, "Bit count field (BITCNT)." },
    { 02015, "System specific field (SYSPEC)." },
    { 02020, "Access control list repeat count field (ACLCNT)." },
    { 02021, "Access control list entry field (ACL)." },
};

const Text miccodes_rms[] = {
    { 00, "Unspecified error." },
    { 01, "operation aborted." },
    { 02, "F11-ACP could not access file." },
    { 03, "\"FILE\" activity precludes operation." },
    { 04, "bad area ID." },
    { 05, "alignment options error." },
    { 06, "allocation quantity too large or 0 value." },
    { 07, "not ANSI \"D\" format." },
    { 010, "allocation options error." },
    { 011, "invalid (i.e., synch) operation at AST level." },
    { 012, "attribute read error." },
    { 013, "attribute write error." },
    { 014, "bucket size too large." },
    { 015, "bucket size too large." },
    { 016, "\"BLN\" length error." },
    { 017, "beginning of file detected." },
    { 020, "private pool address." },
    { 021, "private pool size." },
    { 022, "internal RMS error condition detected." },
    { 023, "cannot connect RAB." },
    { 024, "$UPDATE changed a key without having attribute of XB$CHG set." },
    { 025, "bucket format check-byte failure." },
    { 026, "RSTS/E close function failed." },
    { 027, "invalid or unsupported \"COD\" field." },
    { 030, "F11-ACP could not create file (STV=sys err code)." },
    { 031, "no current record (operation not preceded by GET/FIND)." },
    { 032, "F11-ACP deaccess error during \"CLOSE\"." },
    { 033, "data \"AREA\" number invalid." },
    { 034, "RFA-Accessed record was deleted." },
    { 035, "bad device, or inappropriate device type." },
    { 036, "error in directory name." },
    { 037, "dynamic memory exhausted." },
    { 040, "directory not found." },
    { 041, "device not ready." },
    { 042, "device has positioning error." },
    { 043, "\"DTP\" field invalid." },
    { 044, "duplicate key detected, XB$DUP not set." },
    { 045, "RSX-F11ACP enter function failed." },
    { 046, "operation not selected in \"ORG$\" macro." },
    { 047, "end-of-file." },
    { 050, "expanded string area too short." },
    { 051, "file expiration date not yet reached." },
    { 052, "file extend failure." },
    { 053, "not a valid FAB (\"BID\" NOT = FB$BID)." },
    { 054, "illegal FAC for REC-OP,0, or FB$PUT not set for \"CREATE\"." },
    { 055, "file already exists." },
    { 056, "invalid file I.D." },
    { 057, "invalid flag-bits combination." },
    { 060, "file is locked by other user." },
    { 061, "RSX-F11ACP \"FIND\" function failed." },
    { 062, "file not found." },
    { 063, "error in file name." },
    { 064, "invalid file options." },
    { 065, "DEVICE/FILE full." },
    { 066, "index \"AREA\" number invalid." },
    { 067, "invalid IFI value or unopened file." },
    { 070, "maximum NUM(254) areas/key XABS exceeded." },
    { 071, "$INIT macro never issued." },
    { 072, "operation illegal or invalid for file organization." },
    { 073, "illegal record encountered (with sequential files only)." },
    { 074, "invalid ISI value, on unconnected RAB." },
    { 075, "bad KEY buffer address (KBF=0)." },
    { 076, "invalid KEY field (KEY=0/neg)." },
    { 077, "invalid key-of-reference ($GET/$FIND)." },
    { 0100, "KEY size too large." },
    { 0101, "lowest-level-index \"AREA\" number invalid." },
    { 0102, "not ANSI labeled tape." },
    { 0103, "logical channel busy." },
    { 0104, "logical channel number too large." },
    { 0105, "logical extend error, prior extend still valid." },
    { 0106, "\"LOC\" field invalid." },
    { 0107, "buffer mapping error." },
    { 0110, "F11-ACP could not mark file for deletion." },
    { 0111, "MRN value=neg or relative key>MRN." },
    { 0112, "MRS value=0 for fixed length records. Also 0 for relative files." },
    { 0113, "\"NAM\" block address invalid (NAM=0, or not accessible)." },
    { 0114, "not positioned to EOF (sequential files only)." },
    { 0115, "cannot allocate internal index descriptor." },
    { 0116, "indexed no primary key defined." },
    { 0117, "RSTS/E open function failed." },
    { 0120, "XAB'S not in correct order." },
    { 0121, "invalid file organization value." },
    { 0122, "error in file's prologue (reconstruct file)." },
    { 0123, "\"POS\" field invalid (POS>MRS,STV=XAB indicator)." },
    { 0124, "bad file date field retrieved." },
    { 0125, "privilege violation (OS denies access)." },
    { 0126, "not a valid RAB (\"BID\" NOT=RB$BID)." },
    { 0127, "illegal RAC value." },
    { 0130, "illegal record attributes." },
    { 0131, "invalid record buffer address (\"ODD\", or not word-aligned if BLK-IO)." },
    { 0132, "file read error." },
    { 0133, "record already exists." },
    { 0134, "bad RFA value (RFA=0)." },
    { 0135, "invalid record format." },
    { 0136, "target bucket locked by another stream." },
    { 0137, "RSX-F11 ACP remove function failed." },
    { 0140, "record not found." },
    { 0141, "record not locked." },
    { 0142, "invalid record options." },
    { 0143, "error while reading prologue." },
    { 0144, "invalid RRV record encountered." },
    { 0145, "RAB stream currently active." },
    { 0146, "bad record size (RSZ>MRS, or NOT=MRS if fixed length records)." },
    { 0147, "record too big for user's buffer." },
    { 0150, "primary key out of sequence (RAC=RB$SEQ for $PUT)." },
    { 0151, "\"SHR\" field invalid for file (cannot share sequential files)." },
    { 0152, "\"SIZ field invalid." },
    { 0153, "stack too big for save area." },
    { 0154, "system directive error." },
    { 0155, "index tree error." },
    { 0156, "error in file type extension on FNS too big." },
    { 0157, "invalid user buffer addr (0, odd, or if BLK-IO not word aligned)." },
    { 0160, "invalid user buffer size (USZ=0)." },
    { 0161, "error in version number." },
    { 0162, "invalid volume number." },
    { 0163, "file write error (STV=sys err code)." },
    { 0164, "device is write locked." },
    { 0165, "error while writing prologue." },
    { 0166, "not a valid XAB (@XAB=ODD,STV=XAB indicator)." },
    { 0167, "default directory invalid." },
    { 0170, "cannot access argument list." },
    { 0171, "cannot close file." },
    { 0172, "cannot deliver AST." },
    { 0173, "channel assignment failure (STV=sys err code)." },
    { 0174, "terminal output ignored due to (CNTRL) O." },
    { 0175, "terminal input aborted due to (CNTRL) Y." },
    { 0176, "default filename string address error." },
    { 0177, "invalid device I.D. field." },
    { 0200, "expanded string address error." },
    { 0201, "filename string address error." },
    { 0202, "FSZ field invalid." },
    { 0203, "invalid argument list." },
    { 0204, "known file found." },
    { 0205, "logical name error." },
    { 0206, "node name error." },
    { 0207, "operation successful." },
    { 0210, "record inserted had duplicate key." },
    { 0211, "index update error occurred-record inserted." },
    { 0212, "record locked but read anyway." },
    { 0213, "record inserted in primary o.k.; may not be accessible by secondary keys or RFA." },
    { 0214, "file was created, but not opened." },
    { 0215, "bad prompt buffer address." },
    { 0216, "async. operation pending completion." },
    { 0217, "quoted string error." },
    { 0220, "record header buffer invalid." },
    { 0221, "invalid related file." },
    { 0222, "invalid resultant string size." },
    { 0223, "invalid resultant string address." },
    { 0224, "operation not sequential." },
    { 0225, "operation successful." },
    { 0226, "created file superseded existing version." },
    { 0227, "filename syntax error." },
    { 0230, "time-out period expired." },
    { 0231, "FB$BLK record attribute not supported." },
    { 0232, "bad byte size." },
    { 0233, "cannot disconnect RAB." },
    { 0234, "cannot get JFN for file." },
    { 0235, "cannot open file." },
    { 0236, "bad JFN value." },
    { 0237, "cannot position to end-of-file." },
    { 0240, "cannot truncate file." },
    { 0241, "file is currently in an undefined access is denied." },
    { 0242, "file must be opened for exclusive access." },
    { 0243, "directory full." },
    { 0244, "handler not in system." },
    { 0245, "fatal hardware error." },
    { 0246, "attempt to write beyond EOF." },
    { 0247, "hardware option not present." },
    { 0250, "device not attached." },
    { 0251, "device already attached." },
    { 0252, "device not attachable." },
    { 0253, "sharable resource in use." },
    { 0254, "illegal overlay request." },
    { 0255, "block check or CRC error." },
    { 0256, "caller's nodes exhausted." },
    { 0257, "index file full." },
    { 0260, "file header full." },
    { 0261, "accessed for write." },
    { 0262, "file header checksum failure." },
    { 0263, "attribute control list error." },
    { 0264, "file already accessed on LUN." },
    { 0265, "bad tape format." },
    { 0266, "illegal operation on file descriptor block." },
    { 0267, "rename; 2 different devices." },
    { 0270, "rename; new filename already in use." },
    { 0271, "cannot rename old file system." },
    { 0272, "file already open." },
    { 0273, "parity error on device." },
    { 0274, "end of volume detected." },
    { 0275, "data over-run." },
    { 0276, "bad block on device." },
    { 0277, "end of tape detected." },
    { 0300, "no buffer space for file." },
    { 0301, "file exceeds allocated space -- no blks." },
    { 0302, "specified task not installed." },
    { 0303, "unlock error." },
    { 0304, "no file accessed on LUN." },
    { 0305, "send/receive failure." },
    { 0306, "spool or submit command file failure." },
    { 0307, "no more files." },
    { 0310, "DAP file transfer Checksum error." },
    { 0311, "Quota exceeded" },
    { 0312, "internal network error condition detected." },
    { 0313, "terminal input aborted due to (CNTRL) C." },
    { 0314, "data bucket fill size > bucket size in XAB." },
    { 0315, "invalid expanded string length." },
    { 0316, "illegal bucket format." },
    { 0317, "bucket size of LAN NOT = IAN in XAB." },
    { 0320, "index not initialized." },
    { 0321, "illegal file attributes (corrupt file header)." },
    { 0322, "index bucket fill size > bucket size in XAB." },
    { 0323, "key name buffer not readable or writeable in XAB." },
    { 0324, "index bucket will not hold two keys for key of reference." },
    { 0325, "multi-buffer count invalid (negative value)." },
    { 0326, "network operation failed at remote node." },
    { 0327, "record is already locked." },
    { 0330, "deleted record successfully accessed." },
    { 0331, "retrieved record exceeds specified key value." },
    { 0332, "key XAB not filled in." },
    { 0333, "nonexistent record successfully accessed." },
    { 0334, "unsupported prologue version." },
    { 0335, "illegal key-of-reference in XAB." },
    { 0336, "invalid resultant string length." },
    { 0337, "error updating rrv's, some paths to data may be lost." },
    { 0340, "data types other than string limited to one segment in XAB." },
    { 0341, "reserved" },
    { 0342, "operation not supported over network." },
    { 0343, "error on write behind." },
    { 0344, "invalid wildcard operation." },
    { 0345, "working set full (can not lock buffers in working set.)" },
    { 0346, "directory listing -- error in reading volume-set name, directory name, of file name." },
    { 0347, "directory listing -- error in reading file attributes." },
    { 0350, "directory listing -- protection violation in trying to read the volume-set, directory or file name." },
    { 0351, "directory listing -- protection violation in trying to read file attributes." },
    { 0352, "directory listing -- file attributes do not exist." },
    { 0353, "directory listing -- unable to recover directory list after Continue Transfer (Skip)." },
    { 0354, "sharing not enabled." },
    { 0355, "sharing page count exceeded." },
    { 0356, "UPI bit not set when sharing with BRO set." },
    { 0357, "error in access control string (poor man's route through error)." },
    { 0360, "terminator not seen." },
    { 0361, "bad escape sequence." },
    { 0362, "partial escape sequence." },
    { 0363, "invalid wildcard context value." },
    { 0364, "invalid directory rename operation." },
    { 0365, "user structure (FAB/RAB) became invalid during operation." },
    { 0366, "network file transfer made precludes operation. " },
};

const Text miccodes_10[] = {
    { 00, "Unknown Message Type" },
    { 01, "Configuration Message" },
    { 02, "Attributes Message" },
    { 03, "Access Message" },
    { 04, "Control Message" },
    { 05, "Continue Transfer Message" },
    { 06, "Acknowledge Message" },
    { 07, "Access Complete Message" },
    { 010, "Data Message" },
    { 011, "Status Message" },
    { 012, "Key Definition Attributes Extension Message" },
    { 013, "Allocation Attributes Extension Message" },
    { 014, "Summary Attributes Extension Message" },
    { 015, "Date and Time Attributes Extension Message" },
    { 016, "Protection Attributes Extension Message" },
    { 017, "Name message" },
    { 020, "Access Control List Extended Attributes Message" },
};

template <std::size_t N>
const char *lookup (const Text (&t)[N], unsigned code)
{
    auto it = std::lower_bound (std::begin (t), std::end (t), code,
        [] (const Text &e, unsigned c) { return e.code < c; });
    return it != std::end (t) && it->code == code ? it->text : nullptr;
}

std::string octal (unsigned v, int width)
{
    char buf[16];
    std::snprintf (buf, sizeof buf, "%0*o", width, v);
    return buf;
}

}   // namespace

std::string Status::str () const
{
    const char *mac = lookup (maccodes, maccode);
    std::string macstr = mac ? mac : "Unexpected MACCODE " + octal (maccode, 4);
    const char *mic = nullptr;
    switch (maccode) {
    case 2: case 8: case 9:
        mic = lookup (miccodes_289, miccode); break;
    case 0: case 1: case 4: case 5: case 6: case 7:
        mic = lookup (miccodes_rms, miccode); break;
    case 10:
        mic = lookup (miccodes_10, miccode); break;
    default:
        return macstr + ": ";
    }
    return macstr + ": "
        + (mic ? mic : "Unexpected MICCODE " + octal (miccode, 4));
}

}   // namespace decnet::dap
