# Phase IV endnode with one Multinet circuit.

routing 1.2 --type endnode
node 1.2 CPPND
node 1.1 PYNODE

circuit mul-0 Multinet 127.0.0.1:17700:connect --t3 15

# Matching configuration for the other end:
#   routing 1.1 --type endnode
#   node 1.1 PYNODE
#   node 1.2 CPPND
#   circuit mul-0 Multinet 127.0.0.1:17700:listen
