# Ethernet frames carried in UDP.  No privileges needed.
#
#   udp:<local port>:<peer host>:<peer port>

node 1.2 CPPND
node 1.1 PYNODE
circuit eth-0 Ethernet udp:17802:127.0.0.1:17801 --random-address

# Other end:
#   circuit eth-0 Ethernet udp:17801:127.0.0.1:17802 --random-address
#
# TAP device instead:
#circuit eth-0 Ethernet tap:tap0
